/**
 * [INPUT]: 依赖详细设计第 13 节冻结的 MVP action 集合。
 * [OUTPUT]: 对外提供不能由任意字符串扩张的 AuditAction 枚举。
 * [POS]: audit 事件分类真源，与 V4 数据库 check 约束保持同构。
 * [PROTOCOL]: 变更时更新此头部，然后检查 CLAUDE.md
 */
package com.owndsh.enterprise.audit;

/**
 * MVP 审计动作。
 */
public enum AuditAction {
    LOGIN_SUCCEEDED,
    LOGIN_FAILED,
    LOGOUT,
    IDENTITY_SOURCE_CHANGED,
    USER_LINKED,
    USER_UNLINKED,
    DEVICE_ENROLLED,
    DEVICE_HEARTBEAT,
    DEVICE_REVOKED,
    PROVIDER_CHANGED,
    MODEL_CHANGED,
    MODEL_GRANT_CHANGED,
    MODEL_REQUEST_ACCEPTED,
    MODEL_REQUEST_FINISHED,
    QUOTA_CHANGED,
    QUOTA_REJECTED,
    RESERVATION_RECOVERED,
    PLUGIN_UPLOADED,
    PLUGIN_PUBLISHED,
    PLUGIN_ASSIGNED,
    PLUGIN_DOWNLOADED,
    PLUGIN_INVENTORY_REPORTED,
    SESSION_BATCH_APPENDED,
    SESSION_EXPORTED,
    SESSION_RESTORED,
    SESSION_CONTENT_READ,
    SESSION_DELETED,
    SESSION_EXPIRED,
    ROLE_ASSIGNED,
    USER_STATUS_CHANGED,
    CONFIG_CHANGED
}
