/**
 * [INPUT]: 无外部依赖；字面量由 contracts 真源 OpenAPI 3.1 的 EnterpriseErrorCode 枚举生成。
 * [OUTPUT]: 对外提供 60 个稳定企业错误码联合类型与宿主侧本地码。
 * [POS]: protocol 层的错误码真源，被 http/envelope 与 UI 文案消费；不得手改，改契约后重跑生成。
 * [PROTOCOL]: 变更时更新此头部，然后检查 CLAUDE.md
 */

/** 契约真源的稳定错误码（60 项，enum 与 x-enterprise-error-statuses 一一对应）。 */
export const ENTERPRISE_ERROR_CODES = [
  'ENT_INVALID_REQUEST',
  'ENT_INVALID_REDIRECT_URI',
  'ENT_PKCE_REQUIRED',
  'ENT_PLUGIN_ARTIFACT_INVALID',
  'ENT_PRESET_INVALID_PACKAGE',
  'ENT_PRESET_DEPENDENCIES_INVALID',
  'ENT_PRESET_DEPENDENCY_KIND_UNSUPPORTED',
  'ENT_SKILL_INVALID_PACKAGE',
  'ENT_BRANDING_ASSET_INVALID',
  'ENT_FEEDBACK_INVALID',
  'ENT_FEEDBACK_ATTACHMENT_INVALID',
  'ENT_SESSION_FORMAT_UNSUPPORTED',
  'ENT_AUTH_REQUIRED',
  'ENT_AUTH_CODE_INVALID',
  'ENT_PKCE_INVALID',
  'ENT_AUTH_SESSION_EXPIRED',
  'ENT_PERMISSION_DENIED',
  'ENT_DEVICE_REVOKED',
  'ENT_MODEL_NOT_ASSIGNED',
  'ENT_PLUGIN_NOT_ASSIGNED',
  'ENT_PRESET_NOT_PUBLISHED',
  'ENT_PRESET_VISIBILITY_DENIED',
  'ENT_SKILL_NOT_PUBLISHED',
  'ENT_SKILL_VISIBILITY_DENIED',
  'ENT_RESOURCE_NOT_OWNED',
  'ENT_RESOURCE_NOT_FOUND',
  'ENT_SESSION_CONTENT_EXPIRED',
  'ENT_REVISION_CONFLICT',
  'ENT_LAST_ENTERPRISE_ADMIN',
  'ENT_LAST_MEMBER_IDENTITY',
  'ENT_REQUEST_IN_PROGRESS',
  'ENT_REQUEST_ALREADY_COMPLETED',
  'ENT_SESSION_SEQ_GAP',
  'ENT_SESSION_DIVERGED',
  'ENT_SESSION_SOURCE_DEVICE_CONFLICT',
  'ENT_IDENTITY_ALREADY_LINKED',
  'ENT_DEVICE_ALREADY_BOUND',
  'ENT_FEEDBACK_STATE_CONFLICT',
  'ENT_PRESET_REQUIRES_MISSING',
  'ENT_PRESET_REQUIRES_NOT_PUBLISHED',
  'ENT_REQUEST_TOO_LARGE',
  'ENT_PLUGIN_ARCHIVE_TOO_LARGE',
  'ENT_PRESET_TOO_LARGE',
  'ENT_SKILL_TOO_LARGE',
  'ENT_BRANDING_ASSET_TOO_LARGE',
  'ENT_FEEDBACK_ATTACHMENT_TOO_LARGE',
  'ENT_SESSION_BATCH_TOO_LARGE',
  'ENT_QUOTA_FIVE_HOURS_EXCEEDED',
  'ENT_QUOTA_DAILY_EXCEEDED',
  'ENT_QUOTA_WEEKLY_EXCEEDED',
  'ENT_QUOTA_MONTHLY_EXCEEDED',
  'ENT_QUOTA_RPM_EXCEEDED',
  'ENT_QUOTA_CONCURRENCY_EXCEEDED',
  'ENT_UPSTREAM_RATE_LIMITED',
  'ENT_UPSTREAM_QUOTA_EXCEEDED',
  'ENT_UPSTREAM_AUTH_FAILED',
  'ENT_UPSTREAM_INVALID_RESPONSE',
  'ENT_PLATFORM_UNAVAILABLE',
  'ENT_UPSTREAM_UNAVAILABLE',
  'ENT_UPSTREAM_TIMEOUT',
] as const

export type EnterpriseErrorCode = (typeof ENTERPRISE_ERROR_CODES)[number]

/** 仅存在于客户端进程、不会由中心返回的本地失败码。 */
export const ENTERPRISE_LOCAL_ERROR_CODES = [
  'ENT_AUTH_CANCELLED',
  'ENT_AUTH_TIMEOUT',
  'ENT_PLATFORM_DISPOSED',
  'ENT_NETWORK_ERROR',
  'ENT_RESPONSE_INVALID',
  'ENT_SERVER_URL_INVALID',
  'ENT_ARTIFACT_INTEGRITY_FAILED',
  'ENT_ARTIFACT_UNSIGNED',
  'ENT_ARTIFACT_CORE_PACKAGE',
  'ENT_PLUGIN_COMMAND_FAILED',
] as const

export type EnterpriseLocalErrorCode = (typeof ENTERPRISE_LOCAL_ERROR_CODES)[number]

/** 客户端可呈现的完整错误码集合。 */
export type EnterpriseClientErrorCode = EnterpriseErrorCode | EnterpriseLocalErrorCode
