/**
 * [INPUT]: 依赖 node:fs/promises/node:path、vitest 与 `../src/connector/index.js`（合成段）与 tests/connector-support 夹具
 * [OUTPUT]: 锁定配置型 bundle 的**两个文件逐字节形状**（并与官方 `templates/mcp/` 正文做等价对照）、凭据「只允许引用」的失败码族、`serverName` 的冻结与不截断、摘要/幂等/目录形状/权限，以及"坏描述符一个字节都不落盘"
 * [POS]: 连接器纵深 P0-2「合成段」门禁——断言的是**字节与失败码**，不是"看起来对"；官方模板正文逐字抄录在下方常量里（本机 DSH 安装目录不保证存在，故不读它）
 * [PROTOCOL]: 变更时更新此头部，然后检查 CLAUDE.md
 */

import { readdir, readFile, realpath, stat, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import { afterEach, describe, expect, it } from 'vitest'
import {
  CONNECTOR_BUNDLE_FILENAMES,
  CONNECTOR_BUNDLE_ROOT_SEGMENTS,
  EnterpriseConnectorError,
  MCP_CLIENT_MODULE,
  connectorBundleDigest,
  connectorBundlePackageName,
  connectorRowId,
  connectorServerNameFromId,
  connectorToolNamePrefix,
  renderConnectorBundle,
  synthesizeConnectorBundle,
  type McpConnectorDescriptor,
} from '../src/connector/index.js'
import { cleanupConnectorHomes, connectorDescriptorFixture, makeConnectorHome } from './connector-support.js'

afterEach(cleanupConnectorHomes)

/**
 * 官方 `templates/mcp/cordis.patch.yml` 的正文（**逐字抄录**，见 `docs/plan/mcp-conformance.md` §3）。
 * 本文件用它做"我们的产物与官方模板只差一行 row id"的对照——这是本刀唯一的官方锚点。
 * ★ 抄录件的**锚定核对**（2026-10-06，第十四刀）：下面两个常量已与官方真文件**逐字节/逐字段**比过——
 *   `<dsh>/node_modules/@deepseek-ai/dsh-agent-preset/skills/cordis-plugin-development/templates/mcp/`
 *   的 `cordis.patch.yml`（各 217 字节，逐字相同）与 `package.json`（同 5 个键：name/version/private/type/dsh）。
 *   ⇒ ".replace('    - id: demo-mcp', …)" 这条断言才有意义。**官方模板升级时这里必须重核**（本机不读它是有意的：
 *   门禁要在没有 DSH 安装目录的机器上也能跑）。
 */
const OFFICIAL_PATCH_BODY = `- insert:
    - id: demo-mcp
      name: '@deepseek-ai/dsh-mcp-client'
      config:
        serverName: demo
        transport: streamable-http
        url: http://127.0.0.1:3000/mcp
        failOnStartupError: true
`

/** 官方 `templates/mcp/package.json` 解析后的形状（逐字抄录后解析，避免与我们的缩进写法纠缠）。 */
const OFFICIAL_PACKAGE_JSON = {
  name: '@local/demo-mcp',
  version: '1.0.0',
  private: true,
  type: 'module',
  dsh: { bundle: { patch: './cordis.patch.yml' } },
}

const HTTP_DESCRIPTOR: McpConnectorDescriptor = {
  id: 'demo-mcp',
  displayName: '演示连接器',
  serverName: 'demo',
  endpoint: { transport: 'streamable-http', url: 'http://127.0.0.1:3000/mcp' },
}

/** 去掉我们自己的注释行（官方模板没有注释），只剩 YAML 正文。 */
function withoutCommentLines(patch: string): string {
  return patch.split('\n').filter(line => !line.startsWith('#')).join('\n')
}

function expectCode(run: () => unknown, code: string): void {
  try {
    run()
  } catch (error) {
    expect(error).toBeInstanceOf(EnterpriseConnectorError)
    expect((error as EnterpriseConnectorError).code).toBe(code)
    return
  }
  throw new Error(`expected ${code} to be thrown`)
}

describe('与官方模板的对照（P0-2 的锚点）', () => {
  it('同一份端点的 patch 正文与官方模板**只差 row id 那一行**', () => {
    const rendered = renderConnectorBundle(HTTP_DESCRIPTOR)
    const expected = OFFICIAL_PATCH_BODY.replace('    - id: demo-mcp', `    - id: ${connectorRowId('demo-mcp')}`)
    expect(withoutCommentLines(rendered.cordisPatch)).toBe(expected)
  })

  it('patch 引用的就是官方 mcp-client 包名；package.json 的 dsh.bundle.patch 逐字照官方', () => {
    const rendered = renderConnectorBundle(HTTP_DESCRIPTOR)
    expect(rendered.cordisPatch).toContain(`      name: '${MCP_CLIENT_MODULE}'`)
    const parsed = JSON.parse(rendered.packageJson) as Record<string, unknown>
    expect(parsed).toMatchObject({
      name: connectorBundlePackageName('demo-mcp'),
      private: OFFICIAL_PACKAGE_JSON.private,
      type: OFFICIAL_PACKAGE_JSON.type,
      dsh: OFFICIAL_PACKAGE_JSON.dsh,
      version: OFFICIAL_PACKAGE_JSON.version,
    })
    // 我们只多一个给员工看的 description；官方其它键一个不多一个不少。
    expect(Object.keys(parsed).sort()).toEqual(['description', 'dsh', 'name', 'private', 'type', 'version'])
  })
})

describe('逐字节产物', () => {
  it('stdio：命令/参数/凭据引用与 YAML 引号规则逐字对', () => {
    const rendered = renderConnectorBundle(connectorDescriptorFixture())
    expect(rendered.cordisPatch).toBe(`# generated by dshent-plugin connector synthesis: one @deepseek-ai/dsh-mcp-client row.
# 连接器 ent-demo：字段契约见 docs/plan/mcp-conformance.md §4；请勿手改（改 serverName = 改工具名）。
- insert:
    - id: connector-ent-demo
      name: '@deepseek-ai/dsh-mcp-client'
      config:
        serverName: ent-demo
        transport: stdio
        command: npx
        args:
          - "-y"
          - "@mobilenext/mobile-mcp@latest"
        env:
          DEMO_TOKEN: !!js process.env.ENT_DEMO_TOKEN
        failOnStartupError: true
`)
    expect(rendered.packageJson).toBe(`{
  "name": "dsh-ent-connector-ent-demo",
  "version": "1.0.0",
  "private": true,
  "type": "module",
  "description": "示例连接器",
  "dsh": {
    "bundle": {
      "patch": "./cordis.patch.yml"
    }
  }
}
`)
  })

  it('streamable-http：Bearer 走官方那种模板引用，裸引用走另一种', () => {
    const rendered = renderConnectorBundle({
      id: 'demo-mcp',
      displayName: '演示连接器',
      serverName: 'demo',
      endpoint: {
        transport: 'streamable-http',
        url: 'http://127.0.0.1:3000/mcp',
        headers: [
          { name: 'Authorization', key: 'MCP_TOKEN', scheme: 'Bearer' },
          { name: 'X-Api-Key', key: 'OTHER_KEY' },
        ],
      },
    })
    expect(rendered.cordisPatch).toContain("          Authorization: !!js '`Bearer ${process.env.MCP_TOKEN}`'")
    expect(rendered.cordisPatch).toContain('          X-Api-Key: !!js process.env.OTHER_KEY')
  })

  it('身份与命名助手：row id / 包名 / 工具名前缀 / 摘要', () => {
    const rendered = renderConnectorBundle(HTTP_DESCRIPTOR)
    expect(rendered.rowId).toBe('connector-demo-mcp')
    expect(rendered.packageName).toBe('dsh-ent-connector-demo-mcp')
    expect(rendered.toolNamePrefix).toBe('mcp__demo__')
    expect(rendered.digest).toBe(connectorBundleDigest(rendered.packageJson, rendered.cordisPatch))
    expect(rendered.digest).toMatch(/^[0-9a-f]{64}$/)
    expect(connectorToolNamePrefix('demo')).toBe('mcp__demo__')
    expect(connectorServerNameFromId('ent-demo')).toBe('ent-demo')
  })

  it('同一描述符两次渲染完全一致；配置变一个字符摘要就变', () => {
    const left = renderConnectorBundle(HTTP_DESCRIPTOR)
    const right = renderConnectorBundle(HTTP_DESCRIPTOR)
    expect(right.cordisPatch).toBe(left.cordisPatch)
    expect(right.packageJson).toBe(left.packageJson)
    expect(right.digest).toBe(left.digest)
    const changed = renderConnectorBundle({
      ...HTTP_DESCRIPTOR,
      endpoint: { transport: 'streamable-http', url: 'http://127.0.0.1:3000/mcp2' },
    })
    expect(changed.digest).not.toBe(left.digest)
  })
})

describe('凭据：只允许引用，任何"直接写值"的形状都拒', () => {
  const literalShapes: readonly [string, unknown][] = [
    ['stdio env 写成对象映射（旧写法）', { transport: 'stdio', command: 'npx', env: { DEMO_TOKEN: 'ghp_live_secret' } }],
    ['headers 写成对象映射', { transport: 'streamable-http', url: 'http://x/mcp', headers: { Authorization: 'Bearer sk-live' } }],
    ['数组里直接放字符串', { transport: 'streamable-http', url: 'http://x/mcp', headers: ['sk-live-123'] }],
    ['条目里带 value', { transport: 'stdio', command: 'npx', env: [{ name: 'T', key: 'K', value: 'sk-live' }] }],
    ['条目里带 token', { transport: 'stdio', command: 'npx', env: [{ name: 'T', key: 'K', token: 'x' }] }],
    ['条目里带 secret', { transport: 'streamable-http', url: 'http://x/mcp', headers: [{ name: 'A', key: 'K', secret: 'x' }] }],
  ]

  it.each(literalShapes)('%s ⇒ ENT_CONNECTOR_SECRET_INLINE', (_label, endpoint) => {
    expectCode(() => renderConnectorBundle({
      id: 'demo-mcp',
      displayName: '演示',
      serverName: 'demo',
      endpoint: endpoint as McpConnectorDescriptor['endpoint'],
    }), 'ENT_CONNECTOR_SECRET_INLINE')
  })

  it('凭据键名的形状也受限：值型字符串写不进 key', () => {
    expectCode(() => renderConnectorBundle({
      id: 'demo-mcp',
      displayName: '演示',
      serverName: 'demo',
      endpoint: {
        transport: 'streamable-http',
        url: 'http://x/mcp',
        headers: [{ name: 'Authorization', key: 'Bearer sk-live' }],
      },
    }), 'ENT_CONNECTOR_DECLARATION_INVALID')
  })

  it('stdio 的 env 不接受 Bearer（那是 http 头的引用写法）', () => {
    expectCode(() => renderConnectorBundle({
      id: 'demo-mcp',
      displayName: '演示',
      serverName: 'demo',
      endpoint: {
        transport: 'stdio',
        command: 'npx',
        env: [{ name: 'DEMO_TOKEN', key: 'K', scheme: 'Bearer' }],
      },
    }), 'ENT_CONNECTOR_DECLARATION_INVALID')
  })
})

describe('形状与取值域', () => {
  const base = (overrides: Partial<McpConnectorDescriptor>): McpConnectorDescriptor => ({ ...HTTP_DESCRIPTOR, ...overrides })

  it('transport 只认官方两种（sse 不存在）', () => {
    expectCode(() => renderConnectorBundle(base({
      endpoint: { transport: 'sse', url: 'http://x/mcp' } as unknown as McpConnectorDescriptor['endpoint'],
    })), 'ENT_CONNECTOR_DECLARATION_INVALID')
  })

  it('缺 command / 缺 url 都拒；url 必须是 http(s)', () => {
    expectCode(() => renderConnectorBundle(base({
      endpoint: { transport: 'stdio' } as unknown as McpConnectorDescriptor['endpoint'],
    })), 'ENT_CONNECTOR_DECLARATION_INVALID')
    expectCode(() => renderConnectorBundle(base({
      endpoint: { transport: 'streamable-http' } as unknown as McpConnectorDescriptor['endpoint'],
    })), 'ENT_CONNECTOR_DECLARATION_INVALID')
    expectCode(() => renderConnectorBundle(base({
      endpoint: { transport: 'streamable-http', url: 'file:///tmp/x' },
    })), 'ENT_CONNECTOR_DECLARATION_INVALID')
  })

  it('serverName 必须落在官方取值域（1–32 字符），且**绝不截断**', () => {
    for (const serverName of ['', 'a'.repeat(33), '有中文', 'has space', 'bad$name']) {
      expectCode(() => renderConnectorBundle(base({ serverName })), 'ENT_CONNECTOR_DECLARATION_INVALID')
    }
    expect(connectorServerNameFromId('a'.repeat(32))).toBe('a'.repeat(32))
    expectCode(() => connectorServerNameFromId('a'.repeat(33)), 'ENT_CONNECTOR_DECLARATION_INVALID')
  })

  it('描述符关闭键集：多一个键就拒 —— 于是"想传 failOnStartupError:false"根本传不进来', () => {
    expectCode(() => renderConnectorBundle({
      ...HTTP_DESCRIPTOR,
      failOnStartupError: false,
    } as unknown as McpConnectorDescriptor), 'ENT_CONNECTOR_DECLARATION_INVALID')
    expectCode(() => renderConnectorBundle(base({ id: 'Demo' })), 'ENT_CONNECTOR_DECLARATION_INVALID')
    expect(renderConnectorBundle(base({})).cordisPatch).toContain('        failOnStartupError: true')
  })

  it('重复的头名 / 空的 args / 非 semver 版本都拒', () => {
    expectCode(() => renderConnectorBundle(base({
      endpoint: {
        transport: 'streamable-http',
        url: 'http://x/mcp',
        headers: [{ name: 'X-A', key: 'A' }, { name: 'X-A', key: 'B' }],
      },
    })), 'ENT_CONNECTOR_DECLARATION_INVALID')
    expectCode(() => renderConnectorBundle(base({
      endpoint: { transport: 'stdio', command: 'npx', args: [] },
    })), 'ENT_CONNECTOR_DECLARATION_INVALID')
    expectCode(() => renderConnectorBundle(base({ version: 'v1' })), 'ENT_CONNECTOR_DECLARATION_INVALID')
    expect(renderConnectorBundle(base({ version: '2.1.0-rc.1' })).version).toBe('2.1.0-rc.1')
  })
})

describe('落盘合成', () => {
  it('只写我们自己的落根，恰好两个文件，权限 0700/0600，正文与渲染逐字节相同', async () => {
    const home = await makeConnectorHome()
    const synthesized = await synthesizeConnectorBundle({ dshHome: home }, HTTP_DESCRIPTOR)
    // `home` 可能经符号链接（Android 上 `/data/user/0` ↔ `/data/data`），落盘侧一律拿 realpath 比 realpath。
    const realHome = await realpath(home)
    expect(synthesized.bundleDir.startsWith(join(realHome, ...CONNECTOR_BUNDLE_ROOT_SEGMENTS))).toBe(true)
    expect(synthesized.bundleDir.endsWith(synthesized.digest)).toBe(true)
    expect(synthesized.fileNames).toEqual([...CONNECTOR_BUNDLE_FILENAMES])
    expect((await readdir(synthesized.bundleDir)).sort()).toEqual([...CONNECTOR_BUNDLE_FILENAMES])
    expect(await readFile(join(synthesized.bundleDir, 'cordis.patch.yml'), 'utf8')).toBe(synthesized.cordisPatch)
    expect(await readFile(join(synthesized.bundleDir, 'package.json'), 'utf8')).toBe(synthesized.packageJson)
    expect((await stat(join(synthesized.bundleDir, 'cordis.patch.yml'))).mode & 0o777).toBe(0o600)
    expect((await stat(join(synthesized.bundleDir, 'package.json'))).mode & 0o777).toBe(0o600)
    expect((await stat(synthesized.bundleDir)).mode & 0o777).toBe(0o700)
  })

  it('幂等：同一连接器 + 同一配置 ⇒ 同一目录，第二次不重写也不留暂存目录', async () => {
    const home = await makeConnectorHome()
    const first = await synthesizeConnectorBundle({ dshHome: home }, HTTP_DESCRIPTOR)
    const second = await synthesizeConnectorBundle({ dshHome: home }, HTTP_DESCRIPTOR)
    expect(second.bundleDir).toBe(first.bundleDir)
    const connectorDir = join(home, ...CONNECTOR_BUNDLE_ROOT_SEGMENTS, 'demo-mcp')
    expect((await readdir(connectorDir)).sort()).toEqual([first.digest])
  })

  it('同一连接器换配置 ⇒ 摘要目录并列（"修同一个 bundle"而不是覆盖旧目录）', async () => {
    const home = await makeConnectorHome()
    const first = await synthesizeConnectorBundle({ dshHome: home }, HTTP_DESCRIPTOR)
    const second = await synthesizeConnectorBundle({ dshHome: home }, {
      ...HTTP_DESCRIPTOR,
      endpoint: { transport: 'streamable-http', url: 'http://127.0.0.1:3000/other' },
    })
    expect(second.bundleDir).not.toBe(first.bundleDir)
    const connectorDir = join(home, ...CONNECTOR_BUNDLE_ROOT_SEGMENTS, 'demo-mcp')
    expect((await readdir(connectorDir)).sort()).toEqual([first.digest, second.digest].sort())
  })

  it('摘要目录里多出一个文件 ⇒ 判为可疑并收敛成写失败码', async () => {
    const home = await makeConnectorHome()
    const first = await synthesizeConnectorBundle({ dshHome: home }, HTTP_DESCRIPTOR)
    await writeFile(join(first.bundleDir, 'extra.txt'), 'x', 'utf8')
    await expect(synthesizeConnectorBundle({ dshHome: home }, HTTP_DESCRIPTOR))
      .rejects.toMatchObject({ code: 'ENT_CONNECTOR_BUNDLE_WRITE_FAILED' })
  })

  it('坏描述符一个字节都不落盘（先在内存里校验，再碰磁盘）', async () => {
    const home = await makeConnectorHome()
    await expect(synthesizeConnectorBundle({ dshHome: home }, {
      ...HTTP_DESCRIPTOR,
      endpoint: { transport: 'streamable-http', url: 'http://x/mcp', headers: { Authorization: 'Bearer sk-live' } },
    } as unknown as McpConnectorDescriptor)).rejects.toMatchObject({ code: 'ENT_CONNECTOR_SECRET_INLINE' })
    await expect(readdir(join(home, ...CONNECTOR_BUNDLE_ROOT_SEGMENTS))).rejects.toMatchObject({ code: 'ENOENT' })
  })
  /**
   * **凭据引用矩阵门禁**（26 格 = 13 种"像把字面值抄进配置"的形状 × 2 种传输）。
   *
   * 这是本纵深风险最高的一条边界：这些形状若被接受，字面密钥就会被写进**生成的配置文件**。
   * 断言的是**每一格的确切稳定码**（不是笼统地"抛了"）——`SECRET_INLINE` 告诉运维"你写的是值"，
   * `DECLARATION_INVALID` 才是"名字形状不对"，两者对排障含义不同。
   *
   * ★ 其中 `key 位置写字面值` 这一类（`sk-literal-1234`）在 2026-10-06 第十八刀之前是**被接受的**
   * —— 键名语法当时允许 `-`，而键名会原样进 `!!js process.env.<键名>`（带 `-` 会被 JS 当作减法）。
   * 现在与官方 `REF_PATTERN` 同一把尺，这类形状一律拒。
   */
  it('凭据引用矩阵：13 种泄漏形状 × 2 种传输，每一格的确切拒绝码', () => {
    const cases: readonly [string, unknown, string][] = [
      ['mapping 形态', { DEMO_TOKEN: 'sk-literal' }, 'ENT_CONNECTOR_SECRET_INLINE'],
      ['数组里放裸字符串', ['sk-literal'], 'ENT_CONNECTOR_SECRET_INLINE'],
      ['条目带 value', [{ name: 'X', key: 'Y', value: 'sk-literal' }], 'ENT_CONNECTOR_SECRET_INLINE'],
      ['条目带 token', [{ name: 'X', key: 'Y', token: 'sk-literal' }], 'ENT_CONNECTOR_SECRET_INLINE'],
      ['条目带 secret', [{ name: 'X', key: 'Y', secret: 'sk-literal' }], 'ENT_CONNECTOR_SECRET_INLINE'],
      ['条目带 password', [{ name: 'X', key: 'Y', password: 'sk-literal' }], 'ENT_CONNECTOR_SECRET_INLINE'],
      ['条目带 credential', [{ name: 'X', key: 'Y', credential: 'sk-literal' }], 'ENT_CONNECTOR_SECRET_INLINE'],
      ['条目带 credentials', [{ name: 'X', key: 'Y', credentials: 'sk-literal' }], 'ENT_CONNECTOR_SECRET_INLINE'],
      ['条目带 apiKey', [{ name: 'X', key: 'Y', apiKey: 'sk-literal' }], 'ENT_CONNECTOR_SECRET_INLINE'],
      ['条目带 api_key', [{ name: 'X', key: 'Y', api_key: 'sk-literal' }], 'ENT_CONNECTOR_SECRET_INLINE'],
      ['key 位置写字面值', [{ name: 'X', key: 'sk-literal-1234' }], 'ENT_CONNECTOR_DECLARATION_INVALID'],
      ['key 位置写 Bearer', [{ name: 'X', key: 'Bearer sk' }], 'ENT_CONNECTOR_DECLARATION_INVALID'],
      ['name 位置写值且无 key', [{ name: 'sk-literal' }], 'ENT_CONNECTOR_DECLARATION_INVALID'],
    ]
    let cells = 0
    for (const [label, shape, expected] of cases) {
      for (const transport of ['stdio', 'streamable-http'] as const) {
        cells += 1
        const base = connectorDescriptorFixture({ id: 'demo-mcp', displayName: '演示连接器', serverName: 'demo' })
        const descriptor = transport === 'stdio'
          ? { ...base, endpoint: { transport: 'stdio' as const, command: 'npx', env: shape as never } }
          : {
              ...base,
              endpoint: { transport: 'streamable-http' as const, url: 'https://x.example.com', headers: shape as never },
            }
        try {
          renderConnectorBundle(descriptor)
          throw new Error(`${transport} / ${label} 竟然被接受了`)
        } catch (error) {
          expect(error, `${transport} / ${label}`).toBeInstanceOf(EnterpriseConnectorError)
          expect((error as EnterpriseConnectorError).code, `${transport} / ${label}`).toBe(expected)
        }
      }
    }
    expect(cells).toBe(26)
  })
  /**
   * **描述符变异审计**（与第十八刀的凭据矩阵、第十七刀的声明变异同一手法）：把 `stdio` 的
   * `command/args/env/cwd/transport` 与 `streamable-http` 的 `url/headers/transport` 逐个塞 16 种畸形值
   * （null / 0 / -1 / 1.5 / NaN / 空串 / 空白串 / 真值 / 假值 / 空数组 / 含 null 数组 / 含数字数组 / 空对象 /
   * 带杂键对象 / 超长串），再加一条"未知键"格，共 130 格。
   *
   * 断言**被接受的恰是这 2 格**（双向锁死）：`command` 是任意非空短串、`cwd` 是任意非空短串都合法；
   * 其余一律拒 —— 特别是 `url` 无 http(s) scheme、`args` 里放非字符串、以及任何未知键。
   */
  it('描述符变异审计：130 格里被接受的恰是那 2 个合法情形', () => {
    const BAD: readonly [string, unknown][] = [
      ['null', null], ['zero', 0], ['neg', -1], ['float', 1.5], ['NaN', Number.NaN],
      ['emptyStr', ''], ['blankStr', ' '], ['plainStr', 'x'], ['true', true], ['false', false],
      ['emptyArr', []], ['arrNull', [null]], ['arrNum', [0]], ['obj', {}], ['objJunk', { a: 1 }],
      ['longStr', 'x'.repeat(3000)],
    ]
    const base = connectorDescriptorFixture()
    const build = (transport: 'stdio' | 'streamable-http', field: string, value: unknown): McpConnectorDescriptor => {
      const endpoint: Record<string, unknown> = transport === 'stdio'
        ? { transport: 'stdio', command: 'npx' }
        : { transport: 'streamable-http', url: 'https://x.example.com' }
      if (field === 'extraKey') endpoint['surprise'] = 'x'
      else endpoint[field] = value
      return { ...base, endpoint } as McpConnectorDescriptor
    }
    const accepted: string[] = []
    let cells = 0
    for (const [transport, fields] of [
      ['stdio', ['command', 'args', 'env', 'cwd', 'transport', 'extraKey']],
      ['streamable-http', ['url', 'headers', 'transport', 'extraKey']],
    ] as const) {
      for (const field of fields) {
        const values: readonly [string, unknown][] = field === 'extraKey' ? [['anyValue', 'x']] : BAD
        for (const [label, bad] of values) {
          cells += 1
          try {
            renderConnectorBundle(build(transport, field, bad))
            accepted.push(`${transport} ${field} <- ${label}`)
          } catch {
            // 拒了才是预期
          }
        }
      }
    }
    expect(cells).toBe(130)  // stdio 5×16+1(未知键) + http 3×16+1 = 81+49
    expect(accepted.sort()).toEqual(['stdio command <- plainStr', 'stdio cwd <- plainStr'])
  })
  /**
   * **摘要敏感性矩阵**（幂等的另一半）：摘要既然是"配置变了就重装"的唯一依据，就必须对**每一个**字段敏感
   * —— 反过来，若某个字段被渲染器**静默忽略**，改它不会换摘要，安装段就会跳过本该做的重装。
   *
   * 14 个改动点（含嵌套的 `args` 顺序、`env` 的键名与 name、http 的 url 与 scheme）逐个断言**摘要必变**；
   * 并断言"变化集合 == 全部 14 个"，于是**将来给渲染器加字段却忘了写进产物**时，这条会红。
   *
   * 顺带钉住一个设计后果（不是 bug）：展示名 `displayName` 会作为 `package.json.description` 进产物，
   * 故**纯改名也会产生新摘要、新落点目录、触发一次重装**——这是"摘要 = 产物字节"的自然后果，登记在 §4.2。
   */
  it('摘要敏感性矩阵：14 个改动点全部改变摘要（没有字段被静默忽略）', () => {
    const base = connectorDescriptorFixture()
    const variants: readonly [string, McpConnectorDescriptor][] = [
      ['id', { ...base, id: 'ent-demo2' }],
      ['displayName', { ...base, displayName: '换个名字' }],
      ['serverName', { ...base, serverName: 'demo2' }],
      ['version', { ...base, version: '2.0.0' }],
      ['command', { ...base, endpoint: { transport: 'stdio', command: 'node' } }],
      ['args', { ...base, endpoint: { transport: 'stdio', command: 'npx', args: ['-y', 'x@2'] } }],
      ['args 顺序', { ...base, endpoint: { transport: 'stdio', command: 'npx', args: ['x@2', '-y'] } }],
      ['cwd', { ...base, endpoint: { transport: 'stdio', command: 'npx', cwd: '/tmp' } }],
      ['env 整块缺席', { ...base, endpoint: { transport: 'stdio', command: 'npx' } }],
      ['env 键名', {
        ...base,
        endpoint: { transport: 'stdio', command: 'npx', env: [{ name: 'DEMO_TOKEN', key: 'OTHER_TOKEN' }] },
      }],
      ['env name', {
        ...base,
        endpoint: { transport: 'stdio', command: 'npx', env: [{ name: 'OTHER', key: 'ENT_DEMO_TOKEN' }] },
      }],
      ['换成 http', { ...base, endpoint: { transport: 'streamable-http', url: 'https://x.example.com' } }],
      ['http url', { ...base, endpoint: { transport: 'streamable-http', url: 'https://y.example.com' } }],
      ['http scheme', {
        ...base,
        endpoint: {
          transport: 'streamable-http',
          url: 'https://x.example.com',
          headers: [{ name: 'Authorization', key: 'ENT_DEMO_TOKEN', scheme: 'Bearer' }],
        },
      }],
    ]
    const baseline = renderConnectorBundle(base).digest
    expect(renderConnectorBundle(base).digest).toBe(baseline) // 同配置 ⇒ 同摘要（另一半）
    const unchanged = variants
      .filter(([, descriptor]) => renderConnectorBundle(descriptor).digest === baseline)
      .map(([label]) => label)
    expect(unchanged).toEqual([])
    expect(variants).toHaveLength(14)
  })
})
