/**
 * [INPUT]: 依赖 node:crypto/fs/os/path、vitest、`tests/real-preset-artifact.bin`（真机上那份企业 `.dshpreset` 的**逐字节副本**，1419 B）、src/preset-archive.ts（解包边界）、src/zip-archive.ts（逐条目字节）、src/preset-source.ts（真下载面）+ src/preset-service.ts（本机路由背后那一段）与 src/preset 的合成段
 * [OUTPUT]: 锁死「真实企业制品必须能合成」：夹具 sha256 与四份包内文件**逐字节**、解码事实**逐字段**、合成产物**逐字节**、`status` 那一段**不再抛**且披露与我们真会装的东西一致，并加一条「用真机缓存上那份制品跑合成不报错」的守卫（缓存不在就跳过）
 * [POS]: 合成段对**真实形状**的回归锁 —— fixture 覆盖不到"根 mapping"这个真机制品形状，本文件补上这一格，把真机上 `GET /presets/<id>/status` 的 400 `ENT_PRESET_RECIPE_INVALID` 根因钉成可复跑的断言
 * [PROTOCOL]: 变更时更新此头部，然后检查 CLAUDE.md
 */
import { createHash } from 'node:crypto'
import { existsSync, readFileSync } from 'node:fs'
import { readdir, readFile } from 'node:fs/promises'
import { homedir } from 'node:os'
import { join } from 'node:path'
import { afterEach, describe, expect, it } from 'vitest'
import { decodeDshPresetArchive } from '../src/preset-archive.js'
import { readZipEntries } from '../src/zip-archive.js'
import { createEnterprisePresetInstall, renderPresetBundle, synthesizePresetBundle } from '../src/preset/index.js'
import { createEnterprisePresetRecipeSource } from '../src/preset-source.js'
import { createEnterprisePresetService } from '../src/preset-service.js'
import { cleanupPresetHomes, createFakePresetPort, makePresetHome } from './preset-support.js'

/** 真机上那份制品的 sha256（也是它在 `<dshHome>/enterprise/preset-artifacts/` 下的内容寻址文件名）。 */
const REAL_SHA256 = '63318df370c4a74b97fd222f59c547553288446760de7ed24ffe7a63d9e7072a'

/** 包内四份文件，逐字节抄自真机制品（`unzip` 实测：266 / 118 / 34 / 87 字节，总计 505）。 */
const REAL_FILES: Readonly<Record<string, string>> = {
  'manifest.json': '{\n'
    + '  "format": "dsh-preset",\n'
    + '  "version": "1",\n'
    + '  "id": "demo-weekly-report",\n'
    + '  "name": "示例·周报助手",\n'
    + '  "description": "企业示例配方：周报整理与要点提炼技能",\n'
    + '  "sourceDshVersion": "0.1.0-rc.7",\n'
    + '  "exportedAt": "2026-09-16T12:00:00.000Z"\n'
    + '}\n',
  // 真机制品的形状差异就在这里：`agent.cordis.yml` 是**根 mapping**（name/description/skills），不是根 entry list。
  'preset/agent.cordis.yml': 'name: demo-weekly-report\n'
    + 'description: Enterprise sample preset for weekly report assistance\n'
    + 'skills:\n'
    + '  - weekly-report\n',
  // 官方目录格式的显示元数据文件；真机制品写的是 version + id（没有 name/description/order）。
  'preset/preset.yml': 'version: 1\nid: demo-weekly-report\n',
  // 技能正文：按规划 §K2 我们**不**把它搬进 bundle（它自己也确实没进产物），但必须能逐字节读出来。
  'preset/skills/weekly-report.md': '# Weekly Report\n'
    + '\n'
    + "Summarize the week's work into: highlights, blockers, and next steps.\n",
}

const FIXTURE = readFileSync(new URL('./real-preset-artifact.bin', import.meta.url))

/** 合成产物（两个文件）应当逐字节长这样；`config.name`/`description` 取 manifest（mapping 里那两行是机器标签）。 */
const EXPECTED_PACKAGE_JSON = `{
  "name": "dsh-ent-preset-demo-weekly-report",
  "version": "1.0.0",
  "private": true,
  "type": "module",
  "description": "企业示例配方：周报整理与要点提炼技能",
  "dsh": {
    "bundle": {
      "patch": "./cordis.patch.yml"
    }
  }
}
`

const EXPECTED_CORDIS_PATCH = `# generated by dshent-plugin preset synthesis: one @deepseek-ai/dsh-agent-preset declaration.
# 企业配方 demo-weekly-report：字段映射见 docs/notes/preset-bundle-spike.md §5；请勿手改。
- insert:
    - id: preset-demo-weekly-report
      name: '@deepseek-ai/dsh-agent-preset'
      config:
        id: demo-weekly-report
        name: 示例·周报助手
        description: 企业示例配方：周报整理与要点提炼技能
        plugins: []
`

/** 真机缓存落点（内容寻址文件名就是 sha256）；`$DSH_HOME` 与 `~/.dsh` 都试。 */
function cachedArtifactPath(): string | undefined {
  const homes = [process.env['DSH_HOME'], join(homedir(), '.dsh')]
    .filter((home): home is string => typeof home === 'string' && home !== '')
  return homes
    .map(home => join(home, 'enterprise', 'preset-artifacts', `${REAL_SHA256}.dshpreset`))
    .find(path => existsSync(path))
}

const CACHED = cachedArtifactPath()

/** 真机路由里那个雪花 id 与本机实测过的下载路径（`GET /enterprise/api/v1/local/presets/<id>/status` 背后那一段）。 */
const PACKAGE_ID = '2101601205809025025'
const VERSION_ID = '1902500000000000101'

afterEach(cleanupPresetHomes)

describe('真实企业 `.dshpreset` 制品', () => {
  it('夹具就是真机上那份制品：sha256 逐字节相同、四份包内文件逐字相同', () => {
    expect(createHash('sha256').update(FIXTURE).digest('hex')).toBe(REAL_SHA256)
    expect(FIXTURE.byteLength).toBe(1419)

    const entries = readZipEntries(FIXTURE, {
      maxBytes: 52_428_800, maxEntries: 10_000, maxUncompressedBytes: 209_715_200,
    })
    const files = new Map(entries.filter(entry => !entry.isDirectory).map(entry => [entry.path, entry.bytes]))
    expect([...files.keys()].sort()).toEqual(Object.keys(REAL_FILES).sort())
    for (const [path, text] of Object.entries(REAL_FILES)) {
      expect(files.get(path)?.toString('utf8'), path).toBe(text)
    }
  })

  it('解包：manifest 事实逐字段、根 mapping 正文逐字节、preset.yml 只抄事实不覆盖 manifest', () => {
    const archive = decodeDshPresetArchive(FIXTURE)
    expect(archive.presetId).toBe('demo-weekly-report')
    expect(archive.agentYmlPath).toBe('preset/agent.cordis.yml')
    expect(archive.recipe.manifest).toEqual({
      id: 'demo-weekly-report',
      name: '示例·周报助手',
      description: '企业示例配方：周报整理与要点提炼技能',
    })
    expect(archive.recipe.agentCordisYml).toBe(REAL_FILES['preset/agent.cordis.yml'])
    // `preset/preset.yml` 的 `version: 1` 不是官方元数据键（配方版本只认 manifest）⇒ 不落任何事实；
    // `id` 抄下来只为与 manifest id 对齐，**不**进 manifest 的显示字段。
    expect(archive.recipe.localMetadata).toEqual({ id: 'demo-weekly-report' })
  })

  it('合成：根 mapping 被接受，产物逐字节等于期望（`plugins: []`、skills 不进 bundle），落盘仍恰好两个文件', async () => {
    const archive = decodeDshPresetArchive(FIXTURE)
    const rendered = renderPresetBundle(archive.recipe)

    expect(rendered.agentShape).toBe('mapping')
    expect(rendered.declarationId).toBe('demo-weekly-report')
    expect(rendered.rowId).toBe('preset-demo-weekly-report')
    expect(rendered.packageName).toBe('dsh-ent-preset-demo-weekly-report')
    // 冲突裁决：manifest.json 赢（员工看到中心发布的中文门面名，而不是 mapping 里的机器标签）。
    expect(rendered.displayName).toBe('示例·周报助手')
    expect(rendered.packageJson).toBe(EXPECTED_PACKAGE_JSON)
    expect(rendered.cordisPatch).toBe(EXPECTED_CORDIS_PATCH)
    expect(rendered.digest).toMatch(/^[0-9a-f]{64}$/)
    // 根 mapping 没有任何 `plugins:` ⇒ 空 row 列表；空列表必须写成 `[]`（官方 schema 要数组，`null` 会被拒）。
    expect(rendered.cordisPatch).toContain('        plugins: []')
    // K2：技能**绝不**进 bundle —— 产物里一个 `skills`/`skill-filesystem` 都不许有。
    expect(rendered.cordisPatch).not.toContain('skills')
    expect(rendered.mounts).toEqual([])
    // 但事实不许丢：交回调用方（将来由我们自己的技能管线按引用装，并据此披露）。
    expect(rendered.declaredSkills).toEqual(['weekly-report'])
    expect(rendered.bundleSet.map(item => item.kind)).toEqual(['bundle'])

    // 落盘段也走一遍：真实制品必须真的写出恰好两个文件、逐字节等于上面那两份正文。
    const dshHome = await makePresetHome()
    const written = await synthesizePresetBundle({ dshHome }, archive.recipe)
    expect(written.fileNames).toEqual(['cordis.patch.yml', 'package.json'])
    expect((await readdir(written.bundleDir)).sort()).toEqual(['cordis.patch.yml', 'package.json'])
    expect(await readFile(join(written.bundleDir, 'package.json'), 'utf8')).toBe(EXPECTED_PACKAGE_JSON)
    expect(await readFile(join(written.bundleDir, 'cordis.patch.yml'), 'utf8')).toBe(EXPECTED_CORDIS_PATCH)
  })

  it.skipIf(CACHED === undefined)('真机缓存上那份制品跑合成不报错，且与夹具逐字节同结果', () => {
    const bytes = readFileSync(CACHED!)
    expect(createHash('sha256').update(bytes).digest('hex')).toBe(REAL_SHA256)
    expect(bytes.equals(FIXTURE)).toBe(true)
    const rendered = renderPresetBundle(decodeDshPresetArchive(bytes).recipe)
    expect(rendered.packageJson).toBe(EXPECTED_PACKAGE_JSON)
    expect(rendered.cordisPatch).toBe(EXPECTED_CORDIS_PATCH)
    expect(rendered.declaredSkills).toEqual(['weekly-report'])
  })

  it('真机理品走 status 那一段（既有下载面 → 解包 → 合成 → 三态）不再抛，披露与我们真会装的东西一致', async () => {
    const dshHome = await makePresetHome()
    const profileDir = join(dshHome, 'profile')
    const fake = createFakePresetPort({ profileDir })
    const requests: string[] = []
    const source = createEnterprisePresetRecipeSource({
      dshHome,
      platform: {
        async getPreset(presetPackageId) {
          return {
            id: presetPackageId,
            presetId: 'demo-weekly-report',
            displayName: '示例·周报助手',
            description: '企业示例配方：周报整理与要点提炼技能',
            sourceDshVersion: '0.1.0-rc.7',
            sizeBytes: FIXTURE.byteLength,
            versionId: VERSION_ID,
            sha256: REAL_SHA256,
          }
        },
        async request(input) {
          requests.push(input)
          return new Response(FIXTURE, {
            headers: { 'content-length': String(FIXTURE.byteLength) },
            status: 200,
          })
        },
      },
    })
    const service = createEnterprisePresetService({
      install: createEnterprisePresetInstall({ dshHome, profileDir, port: fake.port }),
      source,
      authorization: { dshHome },
    })

    const status = await service.status(PACKAGE_ID)
    expect(status.presetPackageId).toBe(PACKAGE_ID)
    expect(status.declarationId).toBe('demo-weekly-report')
    expect(status.fingerprint).toMatch(/^[0-9a-f]{64}$/)
    expect(status.authorization.state).toBe('needs-authorization')
    expect(status.inFlight).toBe(false)
    expect(status.installed).toBeNull()
    // 披露 = 我们真会装的那一个最小 bundle；真机制品没有 row ⇒ 没有 mount 项。
    expect(status.disclosure.bundles.map(item => item.name)).toEqual(['dsh-ent-preset-demo-weekly-report'])
    expect(status.disclosure.mounts).toEqual([])
    // 走的是既有那条运行时下载 operation，不是新通道；status 只读，不装任何东西。
    expect(requests).toEqual([`/enterprise/api/v1/presets/versions/${VERSION_ID}/download`])
    expect(fake.installCalls).toEqual([])
    // 脱敏：响应体里不得出现宿主绝对路径。
    expect(JSON.stringify(status)).not.toContain(dshHome)
  })
})
