/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as R403RouteImport } from './routes/403'
import { Route as ConsoleRouteImport } from './routes/_console'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ConsoleIndexRouteImport } from './routes/_console.index'
import { Route as ConsoleAccessRouteImport } from './routes/_console.access'
import { Route as ConsoleAccountRouteImport } from './routes/_console.account'
import { Route as ConsoleActivityRouteImport } from './routes/_console.activity'
import { Route as ConsoleBrandingRouteImport } from './routes/_console.branding'
import { Route as ConsoleFeedbackRouteImport } from './routes/_console.feedback'
import { Route as ConsoleMembersRouteImport } from './routes/_console.members'
import { Route as ConsolePluginsRouteImport } from './routes/_console.plugins'
import { Route as ConsolePresetsRouteImport } from './routes/_console.presets'
import { Route as ConsoleSkillsRouteImport } from './routes/_console.skills'
import { Route as ConsoleAccountIndexRouteImport } from './routes/_console.account.index'
import { Route as ConsoleAccountSecurityRouteImport } from './routes/_console.account.security'
import { Route as EnterpriseAuthCallbackRouteImport } from './routes/enterprise.auth.callback'

const R403Route = R403RouteImport.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/_console',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleIndexRoute = ConsoleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleAccessRoute = ConsoleAccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleAccountRoute = ConsoleAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleActivityRoute = ConsoleActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleBrandingRoute = ConsoleBrandingRouteImport.update({
  id: '/branding',
  path: '/branding',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleFeedbackRoute = ConsoleFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleMembersRoute = ConsoleMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsolePluginsRoute = ConsolePluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsolePresetsRoute = ConsolePresetsRouteImport.update({
  id: '/presets',
  path: '/presets',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleSkillsRoute = ConsoleSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleAccountIndexRoute = ConsoleAccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConsoleAccountRoute,
} as any)
const ConsoleAccountSecurityRoute = ConsoleAccountSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => ConsoleAccountRoute,
} as any)
const EnterpriseAuthCallbackRoute = EnterpriseAuthCallbackRouteImport.update({
  id: '/enterprise/auth/callback',
  path: '/enterprise/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/403': typeof R403Route
  '/': typeof ConsoleIndexRoute
  '/login': typeof LoginRoute
  '/access': typeof ConsoleAccessRoute
  '/account': typeof ConsoleAccountRouteWithChildren
  '/activity': typeof ConsoleActivityRoute
  '/branding': typeof ConsoleBrandingRoute
  '/feedback': typeof ConsoleFeedbackRoute
  '/members': typeof ConsoleMembersRoute
  '/plugins': typeof ConsolePluginsRoute
  '/presets': typeof ConsolePresetsRoute
  '/skills': typeof ConsoleSkillsRoute
  '/account/security': typeof ConsoleAccountSecurityRoute
  '/enterprise/auth/callback': typeof EnterpriseAuthCallbackRoute
  '/account/': typeof ConsoleAccountIndexRoute
}
export interface FileRoutesByTo {
  '/403': typeof R403Route
  '/login': typeof LoginRoute
  '/access': typeof ConsoleAccessRoute
  '/activity': typeof ConsoleActivityRoute
  '/branding': typeof ConsoleBrandingRoute
  '/feedback': typeof ConsoleFeedbackRoute
  '/members': typeof ConsoleMembersRoute
  '/plugins': typeof ConsolePluginsRoute
  '/presets': typeof ConsolePresetsRoute
  '/skills': typeof ConsoleSkillsRoute
  '/': typeof ConsoleIndexRoute
  '/account/security': typeof ConsoleAccountSecurityRoute
  '/enterprise/auth/callback': typeof EnterpriseAuthCallbackRoute
  '/account': typeof ConsoleAccountIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/403': typeof R403Route
  '/_console': typeof ConsoleRouteWithChildren
  '/login': typeof LoginRoute
  '/_console/access': typeof ConsoleAccessRoute
  '/_console/account': typeof ConsoleAccountRouteWithChildren
  '/_console/activity': typeof ConsoleActivityRoute
  '/_console/branding': typeof ConsoleBrandingRoute
  '/_console/feedback': typeof ConsoleFeedbackRoute
  '/_console/members': typeof ConsoleMembersRoute
  '/_console/plugins': typeof ConsolePluginsRoute
  '/_console/presets': typeof ConsolePresetsRoute
  '/_console/skills': typeof ConsoleSkillsRoute
  '/_console/': typeof ConsoleIndexRoute
  '/_console/account/security': typeof ConsoleAccountSecurityRoute
  '/enterprise/auth/callback': typeof EnterpriseAuthCallbackRoute
  '/_console/account/': typeof ConsoleAccountIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/403'
    | '/'
    | '/login'
    | '/access'
    | '/account'
    | '/activity'
    | '/branding'
    | '/feedback'
    | '/members'
    | '/plugins'
    | '/presets'
    | '/skills'
    | '/account/security'
    | '/enterprise/auth/callback'
    | '/account/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/403'
    | '/login'
    | '/access'
    | '/activity'
    | '/branding'
    | '/feedback'
    | '/members'
    | '/plugins'
    | '/presets'
    | '/skills'
    | '/'
    | '/account/security'
    | '/enterprise/auth/callback'
    | '/account'
  id:
    | '__root__'
    | '/403'
    | '/_console'
    | '/login'
    | '/_console/access'
    | '/_console/account'
    | '/_console/activity'
    | '/_console/branding'
    | '/_console/feedback'
    | '/_console/members'
    | '/_console/plugins'
    | '/_console/presets'
    | '/_console/skills'
    | '/_console/'
    | '/_console/account/security'
    | '/enterprise/auth/callback'
    | '/_console/account/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  R403Route: typeof R403Route
  ConsoleRoute: typeof ConsoleRouteWithChildren
  LoginRoute: typeof LoginRoute
  EnterpriseAuthCallbackRoute: typeof EnterpriseAuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/403': {
      id: '/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof R403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_console': {
      id: '/_console'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_console/': {
      id: '/_console/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ConsoleIndexRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/access': {
      id: '/_console/access'
      path: '/access'
      fullPath: '/access'
      preLoaderRoute: typeof ConsoleAccessRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/account': {
      id: '/_console/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof ConsoleAccountRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/activity': {
      id: '/_console/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ConsoleActivityRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/branding': {
      id: '/_console/branding'
      path: '/branding'
      fullPath: '/branding'
      preLoaderRoute: typeof ConsoleBrandingRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/feedback': {
      id: '/_console/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof ConsoleFeedbackRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/members': {
      id: '/_console/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof ConsoleMembersRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/plugins': {
      id: '/_console/plugins'
      path: '/plugins'
      fullPath: '/plugins'
      preLoaderRoute: typeof ConsolePluginsRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/presets': {
      id: '/_console/presets'
      path: '/presets'
      fullPath: '/presets'
      preLoaderRoute: typeof ConsolePresetsRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/skills': {
      id: '/_console/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof ConsoleSkillsRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/_console/account/': {
      id: '/_console/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof ConsoleAccountIndexRouteImport
      parentRoute: typeof ConsoleAccountRoute
    }
    '/_console/account/security': {
      id: '/_console/account/security'
      path: '/security'
      fullPath: '/account/security'
      preLoaderRoute: typeof ConsoleAccountSecurityRouteImport
      parentRoute: typeof ConsoleAccountRoute
    }
    '/enterprise/auth/callback': {
      id: '/enterprise/auth/callback'
      path: '/enterprise/auth/callback'
      fullPath: '/enterprise/auth/callback'
      preLoaderRoute: typeof EnterpriseAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ConsoleAccountRouteChildren {
  ConsoleAccountSecurityRoute: typeof ConsoleAccountSecurityRoute
  ConsoleAccountIndexRoute: typeof ConsoleAccountIndexRoute
}

const ConsoleAccountRouteChildren: ConsoleAccountRouteChildren = {
  ConsoleAccountSecurityRoute: ConsoleAccountSecurityRoute,
  ConsoleAccountIndexRoute: ConsoleAccountIndexRoute,
}

const ConsoleAccountRouteWithChildren = ConsoleAccountRoute._addFileChildren(
  ConsoleAccountRouteChildren,
)

interface ConsoleRouteChildren {
  ConsoleAccessRoute: typeof ConsoleAccessRoute
  ConsoleAccountRoute: typeof ConsoleAccountRouteWithChildren
  ConsoleActivityRoute: typeof ConsoleActivityRoute
  ConsoleBrandingRoute: typeof ConsoleBrandingRoute
  ConsoleFeedbackRoute: typeof ConsoleFeedbackRoute
  ConsoleMembersRoute: typeof ConsoleMembersRoute
  ConsolePluginsRoute: typeof ConsolePluginsRoute
  ConsolePresetsRoute: typeof ConsolePresetsRoute
  ConsoleSkillsRoute: typeof ConsoleSkillsRoute
  ConsoleIndexRoute: typeof ConsoleIndexRoute
}

const ConsoleRouteChildren: ConsoleRouteChildren = {
  ConsoleAccessRoute: ConsoleAccessRoute,
  ConsoleAccountRoute: ConsoleAccountRouteWithChildren,
  ConsoleActivityRoute: ConsoleActivityRoute,
  ConsoleBrandingRoute: ConsoleBrandingRoute,
  ConsoleFeedbackRoute: ConsoleFeedbackRoute,
  ConsoleMembersRoute: ConsoleMembersRoute,
  ConsolePluginsRoute: ConsolePluginsRoute,
  ConsolePresetsRoute: ConsolePresetsRoute,
  ConsoleSkillsRoute: ConsoleSkillsRoute,
  ConsoleIndexRoute: ConsoleIndexRoute,
}

const ConsoleRouteWithChildren =
  ConsoleRoute._addFileChildren(ConsoleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  R403Route: R403Route,
  ConsoleRoute: ConsoleRouteWithChildren,
  LoginRoute: LoginRoute,
  EnterpriseAuthCallbackRoute: EnterpriseAuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
